[project]
name = "ethervyperintermediate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "titanoboa>=0.2.8",
]

[tool.uv.workspace]
members = [
    "web3py-favorites-cu",
]
